### ISSUE TITLE
Certificates namespace not found

### ISSUE THREAD

**Issue by mitchross** [acelinkio/argocd-homelab#465]
When I run through your setup, it seems certificates name space is missing?

what I have done to fix it is a `kubectl apply -f certificate.yaml` after all of argo apps are synced.. 

trying to figure out why... more to come..

**Comment by mitchross** [comment]
Continuing step by step fresh install..

(assume all secrets are made in 1password)

1.  I export in terminal 

export SETUP_NODEIP=192.168.100.76
export SETUP_CLUSTERTOKEN=somethingsomethingsomething


2. login cli eval $(op signin)

3. prep secrets in terminal 

export domain="$(op read op://homelab/stringreplacesecret/domain)"
export cloudflaretunnelid="$(op read op://homelab/stringreplacesecret/cloudflaretunnelid)"
export ciliumipamcidr="$(op read op://homelab/stringreplacesecret/ciliumipamcidr)"
export onepasswordconnect_json="$(op read op://homelab/1passwordconnect/1password-credentials.json | base64)"
export externalsecrets_token="$(op read op://homelab/external-secrets/token)"

4. install k3s master node , cilium, coredns

5.  create namespaces ahead of time

kubectl create namespace argocd
kubectl create secret generic stringreplacesecret --namespace argocd --from-literal domain=$domain --from-literal cloudflaretunnelid=$cloudflaretunnelid --from-literal ciliumipamcidr=$ciliumipamcidr

kubectl create namespace 1passwordconnect
kubectl create secret generic 1passwordconnect --namespace 1passwordconnect --from-literal 1password-credentials.json="$onepasswordconnect_json"

kubectl create namespace external-secrets
kubectl create secret generic 1passwordconnect --namespace external-secrets --from-literal token=$externalsecrets_token

6. PAUSE

confirm healthy pods 

![image](https://github.com/acelinkio/argocd-homelab/assets/6330506/a1d51dda-4ffe-4bc0-a82c-2116309e735a)

7. install argo following setups in setup, and configure

8.  Check all deployments are finished

![image](https://github.com/acelinkio/argocd-homelab/assets/6330506/0c6abe8b-b18c-45e1-9d46-c9796d718e8a)

![image](https://github.com/acelinkio/argocd-homelab/assets/6330506/88dde02b-31c1-4814-9563-a2430f4456d9)


9. Hit certificate error

![image](https://github.com/acelinkio/argocd-homelab/assets/6330506/d14e7ad1-6cd2-46d8-b907-a01d4c7f1fcd)

![image](https://github.com/acelinkio/argocd-homelab/assets/6330506/cc358284-7a60-45ce-a63d-659864c3a7d9)

**Comment by acelinkio** [comment]
Adding some notes so I don't forget to update docs.

* empty repo was hit by find and replace which bombed the gateway crd install.

* entire lab was deployed on single rasberry pi.  Bootstrapping all parts of the lab is intensive.  Argocd is hammering kubernetes api while other workloads are spawning.
